# Generated by Django 4.0.3 on 2022-03-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_account_customer_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_account',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
