# Generated by Django 4.0.3 on 2022-04-29 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_order_orderitem_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='restaurantID',
        ),
    ]
