# Generated by Django 4.0.3 on 2022-05-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_menu_itemimage'),
        ('customer', '0011_alter_deliveryaddress_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='delivery_option',
            field=models.CharField(choices=[('Leave at door', 'Leave at door'), ('Hand it to me', 'Hand it to me')], default='Leave at door', max_length=30),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='status',
            field=models.CharField(choices=[('current status', 'current status'), ('Order Received', 'Order Received'), ('Preparing', 'Preparing'), ('Picked up', 'Picked up'), ('Delivered', 'Delivered')], default='current status', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurantID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurant_account'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='restaurantID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurant_account'),
        ),
    ]
