# Generated by Django 4.0.3 on 2022-05-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_deliveryaddress_delivery_option_deliveryaddress_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='isPaid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
