# Generated by Django 4.0.3 on 2022-05-03 05:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_Account',
            fields=[
                ('is_customer', models.BooleanField(default=False)),
                ('is_restaurant', models.BooleanField(default=True)),
                ('restaurantID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^(?:(?:\\+?1\\s*(?:[.-]\\s*)?)?(?:\\(\\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\\s*\\)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\\s*(?:[.-]\\s*)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\\s*(?:[.-]\\s*)?([0-9]{4})(?:\\s*(?:#|x\\.?|ext\\.?|extension)\\s*(\\d+))?$')])),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('itemImage', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('', 'Choose category'), ('Appetizer', 'Appetizer'), ('Entree', 'Entree'), ('Drink', 'Drink'), ('Dessert', 'Dessert'), ('Side', 'Side')], max_length=20)),
                ('restaurantID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant_account')),
            ],
        ),
    ]
