# Generated by Django 4.0.3 on 2022-03-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menu_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='itemImage',
            field=models.ImageField(blank=True, default='no_image.png', upload_to='images/'),
        ),
    ]
