# Generated by Django 4.0.3 on 2022-03-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_menu_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='itemImage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
